spring.datasource.url=jdbc:postgresql://localhost:5433/medibook
spring.datasource.username=medibook
spring.datasource.password=medibook
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.open-in-view=false
spring.jackson.datatype.datetime.write-dates-as-timestamps=false
